version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbit-net

  producer:
    build: ./producer
    ports:
      - 8080:8080
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-admin}  # Берем из .env или используем 'admin'
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-password}
    depends_on:
      - rabbitmq
    networks:
      - rabbit-net

  consumer:
    build: ./consumer
    ports:
      - 8081:8081
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_USER:-admin}  # Берем из .env или используем 'admin'
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_PASS:-password}
    depends_on:
      - rabbitmq
    networks:
      - rabbit-net

networks:
  rabbit-net:
    driver: bridge
